### PR TITLE
Build 1.3.0

### PR DESCRIPTION
**Pull request by megies**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Starting to test building 1.3.0 release candidates

### CODE REVIEW

**Comment by megies** [comment]
@conda-forge-admin, please rerender

**Comment by trichter** [comment]
I think you can remove `future` from the requirements in `meta.yaml`?

**Comment by megies** [comment]
> I think you can remove `future` from the requirements in `meta.yaml`?

Yes, just waiting on my PR to update `pytest-json_report` feedstock to get merged, so that we get a newer version of it..

**Comment by trichter** [comment]
> not sure why current build is not picking up the recently packaged
v1.4.1

Same in obspy/obspy#3010 and on my own PC

**Comment by megies** [comment]
Can't install it locally either with `>=1.4`, [but the file is there](https://anaconda.org/conda-forge/pytest-json-report/files), probably anaconda is internally only refreshing its repo data only so often..?

**Comment by megies** [comment]
@trichter anaconda repo data just picked up the new version, it can be installed now

**Comment by megies** [comment]
Well, conda docs say this is how to skip pypy builds, but it still builds for pypy
https://conda-forge.org/docs/maintainer/knowledge_base.html

**Comment by megies** [comment]
> Well, conda docs say this is how to skip pypy builds, but it still builds for pypy
> https://conda-forge.org/docs/maintainer/knowledge_base.html

nevermind, overlooked that it needs a rerender

@conda-forge-admin, please rerender

**Comment by megies** [comment]
@trichter ok we're down to one runner's tests failing with the baer picker stuff now

**Comment by megies** [comment]
@conda-forge-admin, please rerender

**Comment by megies** [comment]
@trichter added that conditional libffi pinning, so should be all green here now

**Pull request merged**
