### PR TITLE
Unpin proj4, use cartopy, and Python 3.8

### PR DESCRIPTION
**Pull request by krischer**
Continuation of #37 as this is from my personal repo and conda-forge maintainers can thus push.

### CODE REVIEW

**Comment by krischer** [comment]
@conda-forge-admin please rerender

**Comment by krischer** [comment]
@megies @QuLogic @barsch @ThomasLecocq This PR changes from `basemap` to `cartopy`. Strictly speaking we would not even need to depend on any mapping package and I'd actually prefer this because it imposes less restrictions on any downstream packages.

The downside is that users who want map plots will have to manually install one of the two. I think its worth it. Opinions?

**Comment by megies** [comment]
Right now I don't see a problem with depending on basemap for the conda package. Basemap packages are available also for 3.8 on all archs. What is the motivation to push this right now? Is it causing installation problems I'm not aware of?

EDIT: Obviously thinking about the future (obspy 2.0.0, Py3 only) we should definitly switch to cartopy, probably all-out and get rid of basemap code entirely

To be honest I didn't even notice we didn't have Python 3.8 packages built, no idea why that happened but to me it looks like the re-render just added Py3.8?

In a different issue some conda forge maintainers were advocating deploying two obspy packages, one with basemap, one with cartopy. I don't really like the idea but it's an option, I guess. I also mentioned in various conda tickets that I'm really sad conda doesn't have *a)* the `Recommends:`  and *b)* the side-by-side mutually optional dependency declaration (`numpy, scipy, basemap | cartopy`) mechanics Deb/untu has, these are in my opinion by far the best approach for such stuff that is anywhere in between soft and hard dependencies. But well, gotta make do with what we have.

Also what's it with proj4 and pyproj? I see cartopy depending on "proj" is there a transition to a new package?

**Comment by megies** [comment]
Ah I see we have to add those migration files ourselves to get Py3.8 built. Overlooked that. I'd propose just building Py3.8 without other changes as a starting point @krischer.

**Comment by krischer** [comment]
> Right now I don't see a problem with depending on basemap for the conda package. Basemap packages are available also for 3.8 on all archs. What is the motivation to push this right now? Is it causing installation problems I'm not aware of?

The rational is in the other issue: https://github.com/conda-forge/obspy-feedstock/pull/37#issuecomment-600730518

The latest pyproj and basemap segfault and just don't work for some projections. The two line code snippet in the comment is just an illustration but the orthographic map projection tests in ObsPy also trigger it which is how I discovered it.

> Also what's it with proj4 and pyproj? I see cartopy depending on "proj" is there a transition to a new package?

I'm also a bit confused about some of the dependencies.

All of this together leads me to the conclusion that we should have neither `basemap` nor `cartopy` as a hard conda dependency. If neither is installed ObsPy raises a nice warning that maps cannot be plotted and users can make their own choice. No reason to make our lives more complicated I think.

**Comment by krischer** [comment]
Also `basemap` is no longer maintained so I doubt this will be fixed.

**Comment by megies** [comment]
OK, yeah, maybe let's really get rid of basemap and cartopy in package deps I guess. I really wish conda had a `Recommends` and `|` in dependencies, but hey can't be helped.

**Comment by megies** [comment]
We need to point this out in our conda install instructions then though

**Comment by krischer** [comment]
:) I'll make the changes to this PR and will update the conda installation instructions.

**Comment by krischer** [comment]
For future reference: I also did not know how to update this to Python 3.8 and got help in the conda forge gitter channel.

The migrations file has been extracted from this PR which contains the migration file as well as the rerendered repo: https://github.com/conda-forge/obspy-feedstock/pull/30

**Review by megies — APPROVED** [review]

**Pull request merged**
