### PR TITLE
Package 1.1.1

### PR DESCRIPTION
**Pull request by megies**
This PR will update master to package version 1.1.1 when ready.

### CODE REVIEW

**Comment by megies** [comment]
Currently will test 1.1.1rc1.

**Comment by megies** [comment]
Do **not** merge, this is CI for RC only so far

**Comment by megies** [comment]
I guess these are just crazy network fails??

screenshot from 2019-02-15 15-11-20
screenshot from 2019-02-15 15-11-05

**Comment by megies** [comment]
@conda-forge-admin please rerender

**Comment by megies** [comment]
Just to make sure it's not a rerender issue

**Comment by megies** [comment]
@conda-forge/core what is the policy with build numbers after the compiler switch? Should we use `1000` now for the first build of a new version or should we go back to `0` again?

**Comment by CJ-Wright** [comment]
Back to 0.

**Comment by megies** [comment]
OK thanks @CJ-Wright

**Pull request merged**
