### PR TITLE
Cartopy not basemap

### PR DESCRIPTION
**Pull request by dsentinel**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### Reasons:
 - Basemap is EOL,
 - and giving me spurious issues. (not fully debugged, but)
 - Cartopy resolves, and is intended as basemaps replacement.
### Refs:
EOL announce:
https://matplotlib.org/basemap/users/intro.html#cartopy-new-management-and-eol-announcement
Some direction discussion:
https://github.com/SciTools/cartopy/issues/920
There was a short discussion on our gitter.

### Disclaimer
This may be heavy handed, and inappropriate, but since this or something similar needs to happen at some point in the future, I figured this would at least see how far cartopy gets us.

### CODE REVIEW

**Comment by dsentinel** [comment]
Disscussion started https://github.com/conda-forge/obspy-feedstock/pull/16#issuecomment-430813959

**Comment by megies** [comment]
@dsentinel, like I said in https://github.com/conda-forge/obspy-feedstock/pull/16#issuecomment-430931575, you need to make a fresh branch off master. #16 is completely outdated.

**Comment by dsentinel** [comment]
@megies, sorry I made a mess. What confused me is that obspy's fork of this feedstock is outdated, it's master is old.
What's the dev flow? set pull origin here(conda-forge) and push to obspy's fork?

**Comment by megies** [comment]
> What confused me is that obspy's fork of this feedstock is outdated, it's master is old.

I see. I usually never bother to update main branches on forks. No use in doing so, local main branches should always track the upstream main branches, IMHO.

>  What's the dev flow? set pull origin here(conda-forge) and push to obspy's fork?

Yep. Start branches from `conda-forge/obspy-feedstock` master branch and push to fork.

**Comment by megies** [comment]
I dunno, should we delay the basemap->cartopy switch until 1.2.0 and stick with basemap for the 1.1.1 bug fix release?

**Comment by QuLogic** [comment]
I would wait until the next release which improves compatibility with Matplotlib 3. It should be out after Matplotlib 3.0.1 is made.

**Comment by dsentinel** [comment]
I'd like to get it in as soon as possible for my packages that depend on obspy.
I'll patiently wait, if it's better for everyone else. (I'm already repackaging obspy to distribute packages that depend on unreleased features)
I pushed here to get the conversation started and see if there were any problems building this way, for all the platforms I couldn't test locally on.

**Comment by megies** [comment]
> I'd like to get it in as soon as possible for my packages that depend on obspy.

Well, you can always specify cartopy as a dependency in your own packages? So I don't see a problem..

> (I'm already repackaging obspy to distribute packages that depend on unreleased features)

I guess not for all platforms/pyversions we have on conda-forge, though? Some ~weekly build could be interesting in general, given how long we take to manage a major release. But I'm pretty sure that conda-forge doesnt want to take the load.

**Comment by dsentinel** [comment]
> > I'd like to get it in as soon as possible for my packages that depend on obspy.
> 
> Well, you can always specify cartopy as a dependency in your own packages? So I don't see a problem..

obspy's pkg spec's basemap, and if both are installed obspy chooses basemap, so this also requires an uninstall of basemap.

> 
> > (I'm already repackaging obspy to distribute packages that depend on unreleased features)
> 
> I guess not for all platforms/pyversions we have on conda-forge, though? Some ~weekly build could be interesting in general, given how long we take to manage a major release. But I'm pretty sure that conda-forge doesnt want to take the load.

Just for osx64 and linux64 py36 (3.7 as soon as the feedstock gets there)
Hopefully this will settle down and I can rely on cut versions of obspy before too long, So I wouldn't request such builds, but if others are interested, I'd happily use them.

**Comment by megies** [comment]
> obspy's pkg spec's basemap

Not yet, it doesn't. I guess we just leave basemap/cartopy out of requirements for 1.1.x and 1.2.0 packages and then add cartopy when going to 1.3.0 (which will probably also be py3 only, I guess)?

**Comment by megies** [comment]
Closing in favor of #38. Dependency resolution is hard in conda anyway so might be best to just leave those optionals out.

**Pull request closed without merging**
