### PR TITLE
pin conda-build to 1.21.7 to build obspy 1.0.2

### PR DESCRIPTION
**Pull request by megies**
See conda-forge/staged-recipes#582, build fails with current conda-build 1.21.9

### CODE REVIEW

**Comment by megies** [comment]
I'd like to merge this for our first successful build on all platforms, but somehow I wasn't added as a maintainer for my own recipe.. :stuck_out_tongue_winking_eye: 
Help, please? @ocefpaf, @jakirkham

**Comment by jakirkham** [comment]
No need to bump the build number.

**Comment by jakirkham** [comment]
So you should have gotten an email inviting you to join conda-forge. Once accepted you will be added to the obspy team, which has permissions on this feedstock.

**Comment by megies** [comment]
Oh, sorry, got the email. It got auto-sorted in some github folder that I don't use anymore, only checking github notifications online..

Also got rid of the build number bump commit.

**Comment by jakirkham** [comment]
We could probably just pin this in `conda-forge-build-setup` to be honest. Just not sure which is more work at this point.

cc @pelson

**Comment by megies** [comment]
> We could probably just pin this in conda-forge-build-setup to be honest. Just not sure which is more work at this point.

For me it's not a big deal, current 1.21.x master of `conda-build` builds our package fine. So we won't need this pinning after this current release build.

**Comment by msarahan** [comment]
Great, thanks for that info.  I have just tagged 1.21.11, so that should be available soon.

**Comment by jakirkham** [comment]
>  I have just tagged 1.21.11, so that should be available soon.

LOL ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/23 )

**Pull request merged**
