### PR TITLE
Build long prefix package using conda-build 2.x

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by jjhelmus** [comment]
Comment removed as it was not added to the correct feedstock

**Comment by jjhelmus** [comment]
Sorry about that, commented and closed the wrong PR, re-opening.

**Comment by megies** [comment]
@jjhelmus builds are failing..

**Comment by jjhelmus** [comment]
> @jjhelmus builds are failing..

The build are failing due to some of the unit tests failing.  This appears to happen even when conda build 1.x is used.  
I would appreciate if any of the maintainers could look into the cause of these failing unit tests.

**Comment by krischer** [comment]
That's an unfortunate interaction of the `future` module we use and newer `requests` versions (https://github.com/kennethreitz/requests/issues/3742). So yea - our problem to deal with and not the fault of `conda-build`.

**Comment by megies** [comment]
Ah, right.. didn't notice that was the problem, sorry @jjhelmus. We have new bugfix release coming soon anyway, so maybe we just merge this one into the "next release" PR?

**Comment by jjhelmus** [comment]
> We have new bugfix release coming soon anyway, so maybe we just merge this one into the "next release" PR?

That would be fine.  No other packages which need to be rebuild with long prefixes seems to depend on `obspy` so it should be safe to wait until the next release.  

Feel free to ping me when a new release is made, I'm happy to help ensure that it gets build with a long prefix.

**Comment by jjhelmus** [comment]
Closing this issue for the time being.  Thanks @megies and @krischer for the quick feedback!

**Comment by megies** [comment]
I'll reopen this PR just so that we don't overlook it when building the next release.. probably, I'll manually cherry-pick the contents of this PR at that point..

**Comment by megies** [comment]
@jjhelmus I'm closing this in favor of #6 where I cherry-picked your commits from this one.

**Pull request closed without merging**
